### ISSUE TITLE
changing the speed in the program changes the location of the point.

### ISSUE THREAD

**Issue by spsid13** [skuhl/RobotRun#100]
No matter what the speed of the robot. once the location of a point is recorded. it should reach that location with any speed.

**Comment by neoaero99** [comment]
There is an issue with inverse kinematics: when the speed is too slow, sometimes the robot halts for a time before continuing to move.

**Comment by neoaero99** [comment]
For both linear interpolation and joint interpolation, the margin of error has been reduced, since this issue was open. In addition, the speed of the robot's motion is taken into account for determining when the robot is close enough to its destination.

No matter what, there will always be a margin of error (particularly for linear interpolation), however, I am closing this issue for now.
